### PR TITLE
switch deletion endpoints to the http DELETE verb

### PR DESCRIPTION
**Pull request by certifiedloud**
A fix for #19.

### CODE REVIEW

**Comment by schollz** [comment]
Thanks. This is not quite a fix yet - the lines in the dashboard will also need to be switched to also use DELETE. See here: https://github.com/schollz/find/blob/master/templates/dashboard.tmpl#L366

**Comment by certifiedloud** [comment]
@schollz  Thanks for revewing. 
I updated the dashboard for `delete` and `deleteUser`.

Is there anywhere else that needs to be updated? Documentation perhaps? I did a quick search on github and I didn't find any other places, but I'm sure you know best.

**Comment by certifiedloud** [comment]
Actually, I just looked it up  and I guess you can't do `$.delete()` in jquery. I'll fix this.

**Comment by schollz** [comment]
Thanks, that sounds good!

**Comment by schollz** [comment]
Thanks a lot! I couldn't get the ajax request to work with `data: {}` so I used the `param` instead: https://github.com/schollz/find/commit/6f37f069bfb1bccb4a407e0c00f5356d66d43777.

**Pull request merged**
