### PR TITLE
Added Dockerfile

### PR DESCRIPTION
**Pull request by Thom-x**
I added a simple Dockerfile to build/run the app (on port 8003).

### CODE REVIEW

**Comment by schollz** [comment]
Cool, I don't know how to use Docker so I'll trust you that it works :)

**Comment by Thom-x** [comment]
It works, this image is currently running on my computer :p

**Comment by jeremydk** [comment]
Can you link this repo to the DockerHub so the dockerfile can be pulled directly with a "docker pull schollz/find"?

**Comment by Thom-x** [comment]
You need to register to https://hub.docker.com/ (with schollz as username) and create an "Automatic build" from this repo.

**Comment by schollz** [comment]
Okay thanks. I finally figured out how to use the Docker file, putting my notes here for the time being:

1. [Install Docker](https://docs.docker.com/engine/installation/)
2. `git clone https://github.com/schollz/find.git && cd find`
3. `docker build -t find .`
4. `docker run find`
5. Get IP address for Docker image from host using `docker network inspect bridge | grep IPv4`
6. Send requests to that ipaddress + port!

**Comment by jeremydk** [comment]
Awesome!  When I get a little time, I'll take a look and see about how to follow best practices for this -- we'd want to have the groupname.db files, and possibly a config file (rather than runtimeArgs) pulled into a mapped host volume such that we wouldn't lose all of the fingerprinting work if the container is removed.

**Comment by schollz** [comment]
@jeremydk That sounds cool!

It seems that the data is removed when the container is stopped - is this normal? Is there a way to save a Docker container state before it closes?

**Comment by Thom-x** [comment]
Yes you can bind folders in the container to the host :

`docker run -v /host/path:/container/path -p hostport:containerport find `

This container will bind `/container/path` to `/host/path` on host.
And port `containerport ` to `hostport` on host (no need to get container IP address).

**Comment by jeremydk** [comment]
An application within the container should be considered ephemeral, so ideally we need to externalize state.  That will leave us with a docker command closer to:

docker run \
    --name=find \
    --restart=always \
    -d \
    -v /etc/config/find:/config \
    -p 18003:8003 \
    schollz/find

Breaking this down -->

Give the container the friendly name "find", run in daemon mode, map /etc/config/find on my host to /config within the container, and direct port 18003 on my host to the container's port of 8003.

This eliminates the need to find the IP of the container, and will try to keep the container running.

Assuming the uid of the user running the server has write permissions to the folder, we just need to direct any state we're keeping into /config to make it persist.

**Comment by schollz** [comment]
Thanks @Thom-x. That's useful. I just now realize that its also useful to make periodic commits from the host to persist data and automatically backup! That's much more space-efficient than what I'm currently doing to backup data (tar-balls every day of everything).

@jeremydk That looks great. I will get to work on making config file parsing available as an option for find.

**Comment by schollz** [comment]
I've added an Issue for this: https://github.com/schollz/find/issues/104

**Pull request merged**
