### PR TITLE
An alternative to netsh for Windows

### PR DESCRIPTION
**Pull request by ScottSWu**
Not quite sure if this is a good solution for #40 , but I wrote up an alternative for netsh [here](https://github.com/ScottSWu/windows-wlan-util). This alternative does not require disconnecting / disabling wifi to rescan.

Using netsh:
```
C:\tmp>netsh wlan show networks mode=bssid | md5sum && sleep 10 &&
       netsh wlan show networks mode=bssid | md5sum
1b82be07b85a417ee51d6556adbe0fdc *-
1b82be07b85a417ee51d6556adbe0fdc *-
```

Alternative:
```
C:\tmp>windows-wlan-util.exe query | md5sum && sleep 10 &&
       windows-wlan-util.exe query | md5sum
cc25a5b78f956ba4d912937d3bf6b08e *-
0a898e010bdfcb8dca285d95064c1a18 *-
```

No scanning:
netsh

With scanning:
alternative

A few caveats:
- Requires either distributing the executable (and VC++ runtime) or building it (can cgo do that?)
- Needs about a 10 second pause in-between scans for the list to fully populate (maybe add time between scans as an option?)

### CODE REVIEW

**Comment by schollz** [comment]
That is awesome! Wow, nice job.

Let me test it out and get back to you, but I think this looks like a great alternative.

I think its fine to distribute the executable - you could make a release on your Github . But, because only windows users need it, I'd like to add in a switch for the fingerprint program to download it when nessecary. Basically, if fingerprint detects "windows" it could ask the user "Do you want to download a 3rd party utility for better wifi capture? (y/n)". If "y" then the fingerprint program could download your latest release from Github, check its SHASUM signature, and if everything is good it can use that instead of `netsh`. Otherwise, it could just default to `netsh`.

What do you think?

**Comment by schollz** [comment]
I ran your code but I'm not seeing any output from the scanning list. Let me know if I'm doing something wrong!

Run from Administrator CMD prompt:

```bash
$ windows-wlan-util.exe if
0 Intel(R) Centrino(R) Advanced-N 6200 AGN

$ windows-wlan-util.exe scan

$ windows-wlan-util.exe list

```

**Comment by ScottSWu** [comment]
Hmm, was this built from source or the one in the fork? Which version of windows is this on?

**Comment by schollz** [comment]
It was on Windows 7 and I used your repo from about 10 hours ago.

**Comment by ScottSWu** [comment]
Yup, I accidentally messed that one up (& comes after == in order of operations). I fixed that in the later commit.

**Comment by schollz** [comment]
Just tried it, it works great. You'll have to sync up and do another pull request with the addition since bebus77 made a huge refactoring of the fingerprint program: https://github.com/schollz/find/commit/fd13f80d8dd3466d5106071778353f8e250e1ce4. It should be more flexible now and easier to add this new alternative. Let me know if I can assist!

**Pull request closed without merging**
