### PR TITLE
mqtt changes

### PR DESCRIPTION
**Pull request by sjcliffe**
Add support for existing mqtt server configuration.

### CODE REVIEW

**Comment by tavalin** [comment]
The documentation and usage example should probably have been included in this PR.

**Comment by schollz** [comment]
I can work on updating the documentation.

By the way, the documentation is also open-source, but I keep it hosted on Bitbucket: https://bitbucket.org/schollz/find-web/src/master/docs/content/server.md?at=master&fileviewer=file-view-default.

**Comment by tavalin** [comment]
Cool, thanks! Also, any chance you could rebase your dev branch to include this? It might sort out the Docker issue I'm having with the conf file.

**Comment by sjcliffe** [comment]
I'll update the documentation.

**Comment by schollz** [comment]
@sjcliffe Thanks, its live now.

@tavalin Yeah, I just pulled it into the dev branch now.

**Comment by lwis** [comment]
🎉  this is brilliant, thanks @sjcliffe & @schollz

**Pull request merged**
