### PR TITLE
Update app name and help section

### PR DESCRIPTION
**Pull request by G07cha**
- Rename fingerprint to find
- Remove OS X as unsupported platform from readme(works on my laptop)
- Update usage guide(aka help section)

### CODE REVIEW

**Comment by schollz** [comment]
Thanks, it seems that we have Windows and OS X support now thanks to lots of kind folks. Could you update the readme with that?

**Comment by G07cha** [comment]
Sure, should I completely remove "Contributing" section, or leave it empty?

**Comment by schollz** [comment]
Leave it there as I can also use improvements. In fact, someone just found a Windows Wifi scanning downside: https://github.com/schollz/find/issues/40 that could use a helping hand to improve.

**Comment by G07cha** [comment]
Yeah, that's why I'm didn't removed "Windows contribution help request". So I we just leave it here as is, or you still want to remove it?

**Comment by schollz** [comment]
Okay, great I wasn't sure if you saw that.
This looks good then. I will merge it later tonight and build binaries for all the OS for a new release.

**Comment by schollz** [comment]
Can't update until https://github.com/schollz/find/issues/53 is resolved

**Pull request closed without merging**
